spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: s3nh@D5!
  jpa:
    hibernate:
      dll-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect